### ISSUE TITLE
Error when optimisation step size less than 1 (CLOVER HPC)

### ISSUE THREAD

**Issue by hamishbeath** [CLOVER-energy/CLOVER#98] opened 2022-07-19 13:26 UTC
### Describe the bug
When using PV or storage step sizes less than one for CLOVER HPC, the optimisations fail giving the error shown below.

### To Reproduce
1. Set optimisation step size to <1
2. Run optimisation on HPC
3. Check logs
4. See error.

### Expected behaviour
CLOVER 4 permitted a step size of less than one. For household or smaller community systems being able to set the step size to match component sizes (e.g. 300w panel or 0.2kWh batteries) is important.

### Error Text
    15/07/2022 04:05:30 PM: Angola_2020_ssp1_tier1_SHS_clover_1: ERROR: [91mAn unexpected error occurred running a CLOVER optimisation. See logs/clover.log for details: range() arg 3 must not be zero[0m
    Traceback (most recent call last):
      File "/rds/general/user/hrb16/home/anaconda3/envs/clover/lib/python3.7/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/rds/general/user/hrb16/home/anaconda3/envs/clover/lib/python3.7/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/rds/general/user/hrb16/home/CLOVER/src/clover/scripts/hpc.py", line 165, in <module>
        main(sys.argv[1:])
      File "/rds/general/user/hrb16/home/CLOVER/src/clover/scripts/hpc.py", line 161, in main
        clover_main(clover_arguments, True, hpc_job_number)
      File "/rds/general/user/hrb16/home/CLOVER/src/clover/__main__.py", line 1196, in main
        electric_yearly_load_statistics,
      File "/rds/general/user/hrb16/home/CLOVER/src/clover/optimisation/optimisation.py", line 1421, in multiple_optimisation_step
        yearly_electric_load_statistics,
      File "/rds/general/user/hrb16/home/CLOVER/src/clover/optimisation/optimisation.py", line 1077, in _optimisation_step
        yearly_electric_load_statistics,
      File "/rds/general/user/hrb16/home/CLOVER/src/clover/optimisation/optimisation.py", line 768, in _simulation_iteration
        range(int(pv_sizes.min), int(pv_size_max + pv_sizes.step), int(pv_sizes.step)),
    ValueError: range() arg 3 must not be zero

**Comment by BenWinchester** [comment] 2022-07-25 14:46
As discussed, worth checking whether non-integer sizes (e.g., 1.5) rather than being less than one is the issue :smile:

**Comment by BenWinchester** [comment] 2022-07-26 07:40
@hamishbeath , which branch are you on? I.E., `master` or `dev`? :smile:

**Comment by BenWinchester** [comment] 2022-07-26 16:55
## :bug: Bug found 🔍 
The bug seems to be due to how the size information for the optimisation is set up prior to each optimisation for the various components:
```python
    simulation_pv_sizes: List[int] = sorted(
        range(int(pv_sizes.min), int(pv_size_max + pv_sizes.step), int(pv_sizes.step)),
        reverse=True,
    )
    simulation_storage_sizes: List[int] = sorted(
        range(
            int(storage_sizes.min),
            int(storage_size_max + storage_sizes.step),
            int(storage_sizes.step),
        ),
        reverse=True,
    )
```

Currently, as can be seen in the above code snippet, and can be found [here](https://github.com/CLOVER-energy/CLOVER/blob/fc4e44bf73c0e695b3c11cd20985fe64e2ebedf8/src/clover/optimisation/optimisation.py#L767) in the #86 release of CLOVER, this issue is caused by all the sizing information being cast to integers.

## ❗ Impact
This bug appears in production code, on the `master` branch, and will affect **all** users who are currently attempting to run CLOVER optimisations with non-integer step sizes. 

## 💬 Potential fixes
### Everything floats
The most obvious potential fix is to leave everything as is, i.e., the users' input information can be used directly. The only check required would be that this information is a float. Doing this would affect the way that CLOVER generates the potential sizes: currently, it uses the minimum, maximum, and step size as part of python's in-built `range()` function in order to generate the sizes that need to be probed. However, this logic would need to be changed in order to accommodate non-integer inputs.

### Some things float
Converters, such as air conditioners, don't really come in half sizes. A better fix might be to have some things allowable as non-integers (e.g., PV, if using kWp) but not everything (e.g., converters would stay as integers). In this case, there would need to be more helpful information outputted to the user than what is currently written to the logs so that the users can tell what they've done wrong and what they need to fix.

### Nothing floats
CLOVER allows for the pv "unit," i.e., how much kWp of power to assign to each step in the optimisation, to be changed when defining the panels. This functionality is quite useful, in that, a user can define a panel to be sized at, e.g., 350 Wp of power, and then optimise based on a finite series of panels. This corresponds, more often, to real-world situations as companies and individuals can't install half panels. I.E., the user guide, wiki, and documentation could be updated to point users to this functionality so that they're aware of what CLOVER can do.

#### Do batteries float?
If this option is selected, as it is potentially the one that requires the least effort, then a check needs to be done as to whether batteries can have a capacity specified in the same way as PV panels, and, if not, this functionality needs to be introduced so that they mirror PV panels better.

**Closed** 2022-07-28 06:53 UTC
Labels: bug, HPC
